### ISSUE TITLE
add icons in the footer ?

### ISSUE THREAD

**Issue by ahmvdev** [ahmvdev/businesscardprac#1]
Add icons in the footer cause i cannot figure out how to. If anyone can tell me I would appreciate it or add them yourselves so I can learn

Github and LinkedIn will be fine

**Comment by mathushabai** [comment]
Hi, could I be assigned to help with this issue?

**Comment by UNF-Derockjr** [comment]
At the footer of all pages or just your info.jsx page?

**Comment by ahmvdev** [comment]
> At the footer of all pages or just your info.jsx page?

only info.jsx ofc

**Comment by ahmvdev** [comment]
> Hi, could I be assigned to help with this issue?

assigned it to you
